Librinfo\CRMBundle\Entity\Category:
    type: entity
    fields:
        name:
            type: string
            length: 255
    manyToMany:
        organisms:
            targetEntity: Organism
            mappedBy: categories
