Librinfo\CRMBundle\Entity\Category:
    type: entity
    repositoryClass: Librinfo\CRMBundle\Entity\Repository\CategoryRepository

    fields: ~

    oneToMany:
        organisms:
            targetEntity: Librinfo\CRMBundle\Entity\Organism
            mappedBy: category
            cascade: [ persist ]
