Librinfo\CRMBundle\Entity\Category:
    type: entity
    fields: ~
    manyToMany:
        organisms:
            targetEntity:   Librinfo\CRMBundle\Entity\Organism
            mappedBy:     categories
