Librinfo\CRMBundle\Entity\Contact:
    type: entity
    fields:
        firstname:
            type:       string(255)
            nullable:   true
        shortname:
            type:       string(255)
            nullable:   true
        title:
            type:       string(255)
            nullable:   true
        flashOnControl:
            type:       string
            nullable:   true
        password:
            type:       string(255)
            nullable:   true
        familyContact:
            type:       boolean
            nullable:   true
        culture:
            type:       string(2)
            nullable:   true       
    oneToMany:
        phones:
            targetEntity: ContactPhone
            mappedBy: contact
        positions:
            targetEntity: Position
            mappedBy: contact       
            cascade:
                - persist            
    manyToMany:
        circles:
            targetEntity: Librinfo\CRMBundle\Entity\Circle
            inversedBy: contacts
            joinTable:
                name: librinfo_crm_contact_circle
                joinColumns:
                    contact_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    circle_id:
                        referencedColumnName: id
