# info: ContactPhone extends Phone (mapped superclass)

Librinfo\CRMBundle\Entity\ContactPhone:
    type: entity
    manyToOne:
        contact:
            targetEntity: Librinfo\CRMBundle\Entity\Contact
            inversedBy: phones
            joinColumn:
                name: contact_id
            cascade: [ persist ]