Librinfo\CRMBundle\Entity\Organism:
    type: entity
    fields:
        url:
            type:       string
            length:     255
            nullable:   true
        administrativeNumber:
            type:       string
            length:     255
            nullable:   true

    oneToMany:
        phones:
            targetEntity: OrganismPhone
            mappedBy: organism
            cascade: [ persist ]
        positions:
            targetEntity: Position
            mappedBy: organism
            cascade:
                - persist

    manyToMany:
        circles:
            targetEntity: Librinfo\CRMBundle\Entity\Circle
            inversedBy: organisms
            joinTable:
                name: librinfo_crm_organism_circle

    manyToOne:
        category:
            targetEntity: Librinfo\CRMBundle\Entity\Category
            inversedBy: organisms
            joinColumn:
                name: category_id
                onDelete: set null
            cascade: [ persist ]

