Librinfo\CRMBundle\Entity\Position:
    type: entity
    fields:
        phone:
            type: string
            length: 255
            nullable: true
        description:
            type: text
            nullable: true
        department:
            type: string
            length: 255
            nullable: true
    manyToOne:
        contact:
            targetEntity: Librinfo\CRMBundle\Entity\Contact
            inversedBy: positions
#            cascade:
#                - persist
#            joinColumn:
#                name: contact
#                referencedColumnName: id
        organism:
            targetEntity: Librinfo\CRMBundle\Entity\Organism
            inversedBy: positions
        position_type:
            targetEntity: Librinfo\CRMBundle\Entity\PositionType
        

    lifecycleCallbacks: {  }
