Librinfo\CRMBundle\Entity\Position:
    type: entity
    fields:
        phone:
            type: string
            length: 255
            nullable: true
        description:
            type: text
            nullable: true
        department:
            type: string
            length: 255
            nullable: true
    manyToOne:
        contact:
            targetEntity: Librinfo\CRMBundle\Entity\Contact
            inversedBy: positions
            joinColumn:
                name: contact_id
                referencedColumnName: id
                nullable: false
            cascade:
                - persist
        organism:
            targetEntity: Librinfo\CRMBundle\Entity\Organism
            inversedBy: positions
            joinColumn:
                name: organism_id
                referencedColumnName: id
                nullable: false
            cascade:
                - persist
        position_type:
            targetEntity: Librinfo\CRMBundle\Entity\PositionType
        

    lifecycleCallbacks: {  }
