Librinfo\CRMBundle\Entity\Role:
    type: entity
    fields:
        name:
            type:       string
            length:     255
    manyToMany:
        contactGroups:
            targetEntity: Librinfo\CRMBundle\Entity\ContactGroup
            mappedBy: roles
            joinTable:
                name: librinfo_crm_contactgroups_roles
                joinColumns:
                    role_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    contact_group_id:
                        referencedColumnName: id
