Librinfo\CRMBundle\Entity\Role:
    type: entity
    fields: ~
    manyToMany:
        contactGroups:
            targetEntity: Librinfo\CRMBundle\Entity\ContactGroup
            mappedBy: roles
            joinTable:
                name: ~
                joinColumns:
                    role_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    contact_group_id:
                        referencedColumnName: id
