services:
    app.admin.contact:
        class: Librinfo\CRMBundle\Admin\ContactAdminConcrete
        arguments: [~, Librinfo\CRMBundle\Entity\Contact, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Customers Relationship Management, label: Contact}

    app.admin.category:
        class: Librinfo\CRMBundle\Admin\CategoryAdminConcrete
        arguments: [~, Librinfo\CRMBundle\Entity\Category, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Customers Relationship Management, label: Category}

    app.admin.organism:
        class: Librinfo\CRMBundle\Admin\OrganismAdminConcrete
        arguments: [~, Librinfo\CRMBundle\Entity\Organism, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Customers Relationship Management, label: Organism}

    app.admin.role:
        class: Librinfo\CRMBundle\Admin\RoleAdminConcrete
        arguments: [~, Librinfo\CRMBundle\Entity\Role, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Customers Relationship Management, label: Role}

    app.admin.contactgroup:
        class: Librinfo\CRMBundle\Admin\ContactGroupAdminConcrete
        arguments: [~, Librinfo\CRMBundle\Entity\ContactGroup, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Customers Relationship Management, label: Group}
