parameters:
    librinfo:


############
# CATEGORY
############

        Librinfo\CRMBundle\Entity\Category:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    General:
                        '':
                            name:
                                type: text
                            parentNode:
                                type: librinfo_baseentities_treeable
                                class: Librinfo\CRMBundle\Entity\Category
                                required: false
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    name: ~
                    _action:
                        type: actions
                        actions:
                            show: ~
                            edit: ~
                            delete: ~


############
# ORGANISM
############

        Librinfo\CRMBundle\Entity\Organism:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                remove: [description]
                add:
                    General:
                        '':
                            categories:
                                type: librinfo_baseentities_treeablechoice
                                class: Librinfo\CRMBundle\Entity\Category
                                required: false
                                multiple: true
                            url: ~
                            administrativeNumber: ~
                            description:
                                type: textarea
                        Phones:
                            phones:
                                type: sonata_type_collection
                                by_reference: false
                                type_options:
                                    required: false
                                    btn_add: false
                                required: false
                                label: false
                                _options:
                                    edit: inline
                                    inline: table
                                    allow_delete: true
                    _options:
                        tabsOrder:
                            - General
                            - Positions
                            - Specifics
                Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    url: ~
                    administrativeNumber: ~
                    categories: ~
                    _action:
                        type: actions
                        actions:
                            show: ~
                            edit: ~
                            delete: ~
                remove:
                    - zip
                    - city
                    - country
                    - email
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    name: ~

##########
# ORGANISMPHONE
##########

        Librinfo\CRMBundle\Entity\OrganismPhone:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    phoneType: ~
                    number: ~
                    #organism: ~
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    organism: ~
                    phoneType: ~
                    number: ~
                    _action:
                        type: actions
                        actions:
                            show: ~
                            edit: ~
                            delete: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    number: ~
                    #contact: ~

###########
# CONTACT
###########

        Librinfo\CRMBundle\Entity\Contact:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
                add:
                    default:
                        _options:
                            groupsOrder:
                                - Contact
                                - Phones
                                - Address
                                - Description
                                - Positions
                                - Ticketing
                                - Communication
                                - Email
                                - Misc
            Sonata\AdminBundle\Form\FormMapper:
                remove: [description]
                add:
                    General:
                        '':
                            title: ~
                            firstname: ~
                            description:
                                type: textarea
                            _options:
                                fieldsOrder:
                                    - title
                                    - firstname
                                    - name
                                    - email
                                    - circles
                                    - description
                        Phones:
                            phones:
                                type: sonata_type_collection
                                by_reference: false
                                type_options:
                                    required: false
                                    btn_add: false
                                required: false
                                label: false
                                _options:
                                    edit: inline
                                    inline: table
                                    allow_delete: true
                        _options:
                            groupsOrder:
                                - ''
                                - Phones
                                - Address
                    Sales:
                        Ticketing:
                            flashOnControl: ~
                    Specifics:
                        Communication:
                            culture: ~
                            _options:
                                fieldsOrder:
                                    - culture
                        _options:
                            groupsOrder:
                                - Communication
                                - Address
                                - Email
                                - Misc
                    _options:
                        tabsOrder:
                            - General
                            - Positions
                            - Sales
                            - Specifics
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    title: ~
                    firstname: ~
                    _options:
                        fieldsOrder:
                            - title
                            - firstname
                            - name
                            - email
                    _action:
                        type: actions
                        actions:
                            show: ~
                            edit: ~
                            delete: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    title: ~
                    firstname: ~
                    shortname: ~
                    familyContact: ~
                    culture: ~
                    npai: ~
                    emailNpai: ~
                    emailNoNewsletter: ~
                    _options:
                        fieldsOrder:
                            - title
                            - firstname
                            - name
                            - email
                            - zip
                            - city
                            - country
                            - familyContact
                            - culture
                            - npai
                            - emailNpai
                            - emailNoNewsletter

##########
# CONTACTPHONE
##########

        Librinfo\CRMBundle\Entity\ContactPhone:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    phoneType: ~
                    number: ~
                    #contact: ~
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    contact: ~
                    phoneType: ~
                    number: ~

                    _action:
                        type: actions
                        actions:
                            show: ~
                            edit: ~
                            delete: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    number: ~
                    #contact: ~

##########
# CIRCLE
##########

        Librinfo\CRMBundle\Entity\Circle:
            managedManyToMany: [contacts, organisms]
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                remove: [owner]
                add:
                    General:
                        '':
                            owner:
                                type: sonata_type_model_autocomplete
                                by_reference: false
                                property: username
                                multiple: false
                                required: false
                    Members:
                        '':
                            contacts:
                                type: sonata_type_model_autocomplete
                                by_reference: false
                                property: name
                                multiple: true
                                required: false
                            organisms:
                                type: sonata_type_model_autocomplete
                                by_reference: false
                                property: name
                                multiple: true
                                required: false
                    _options:
                        tabsOrder:
                            - General
                            - Members
                            - Specifics
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    owner: ~
                    _action:
                        type: actions
                        actions:
                            show: ~
                            edit: ~
                            delete: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:


############
# POSITION
############

        Librinfo\CRMBundle\Entity\Position:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                remove: [email, label, emailNpai, emailNoNewsletter, circles, description]
                add:
                    '':
                        Position:
                            contact:
                                type: sonata_type_model_autocomplete
                                by_reference: false
                                property: name
                            organism:
                                type: sonata_type_model_autocomplete
                                by_reference: false
                                property: name
                            positionType:
                                placeholder: ''
                            label: ~
                            email:
                                type: email
                            phone:
                                label: Phone number
                            circles: ~
                            department: ~
                            description:
                                type: textarea
                            _options:
                                fieldsOrder:
                                    - contact
                                    - organism
                                    - positionType
                                    - label
                                    - email
                                    - phone
                                    - circles
                                    - department
                                    - description
                        Specifics:
                            emailNpai: ~
                            emailNoNewsletter: ~
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    contact: ~
                    position_type: ~
                    organism: ~
                    _action:
                        type: actions
                        actions:
                            show: ~
                            edit: ~
                            delete: ~


############
# CIRCLABLE Trait
############

        Librinfo\CRMBundle\Entity\Traits\Circlable:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    General:
                        '':
                            circles: ~

############
# POSITIONABLE Trait
############

        Librinfo\CRMBundle\Entity\Traits\Positionable:
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    '':
                        Positions:
                            positions:
                                _options:
                                    initializeAssociationAdmin: true
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    Positions:
                        Positions:
                            positions:
                                type: sonata_type_collection
                                by_reference: false
                                type_options:
                                    required: false
                                    btn_add: false
                                required: false
                                label: false
                                _options:
                                    edit: inline
                                    #inline: table
                                    allow_delete: true

#################
# POSITION_TYPE
#################

        Librinfo\CRMBundle\Entity\PositionType:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    _action:
                        type: actions
                        actions:
                            show: ~
                            edit: ~
                            delete: ~

