parameters:
    librinfo:


############
# CATEGORY
############

        Librinfo\CRMBundle\Entity\Category:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    General:
                        '':
                            name:
                                type: text
                            parentNode:
                                type: treeable
                                class: Librinfo\CRMBundle\Entity\Category
                                required: false
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    name: ~
                    _action:
                        type: actions
                        actions:
                            show: ~
                            edit: ~
                            delete: ~


############
# ORGANISM
############

        Librinfo\CRMBundle\Entity\Organism:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    General:
                        '':
                            categories:
                                type: treeable_choice
                                class: Librinfo\CRMBundle\Entity\Category
                                required: false
                                multiple: true
                            url: ~
                            administrativeNumber: ~
                    _options:
                        tabsOrder:
                            - General
                            - Specifics
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    url: ~
                    administrativeNumber: ~
                    categories: ~
                    _action:
                        type: actions
                        actions:
                            show: ~
                            edit: ~
                            delete: ~
                remove:
                    - zip
                    - city
                    - country
                    - email
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    name: ~


###########
# CONTACT
###########

        Librinfo\CRMBundle\Entity\Contact:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    General:
                        '':
                            title: ~
                            firstname: ~
                            phones:
                                by_reference: false
                                expanded: false

                            _options:
                                fieldsOrder:
                                   - title
                                   - firstname
                                   - name
                                   - email
                                   - phones
                    Sales:
                        Ticketing:
                            flashOnControl: ~
                    Specifics:
                        Communication:
                            culture: ~
                            _options:
                                fieldsOrder:
                                    - culture
                    Relationships:
                        '':
                            circles: ~
                        'Organisms': 
                            positions: 
                                type: sonata_type_collection
                                type_options:
                                    required: false
                                    btn_add: false
                                required: false
                                label: false
                    _options:
                        tabsOrder:
                            - General
                            - Relationships
                            - Sales
                            - Specifics
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    title: ~
                    firstname: ~
                    _options:
                        fieldsOrder:
                            - title
                            - firstname
                            - name
                            - email
                    _action:
                        type: actions
                        actions:
                            show: ~
                            edit: ~
                            delete: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    title: ~
                    firstname: ~
                    shortname: ~
                    familyContact: ~
                    culture: ~
                    npai: ~
                    emailNpai: ~
                    emailNoNewsletter: ~
                    _options:
                        fieldsOrder:
                            - title
                            - firstname
                            - name
                            - email
                            - zip
                            - city
                            - country
                            - familyContact
                            - culture
                            - npai
                            - emailNpai
                            - emailNoNewsletter


        Librinfo\CRMBundle\Entity\ContactPhone:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    number: ~
                    #contact: ~
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    number: ~
                    contact.firstname: ~
                    _action:
                        type: actions
                        actions:
                            show: ~
                            edit: ~
                            delete: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    number: ~
                    #contact: ~

##########
# CIRCLE
##########

        Librinfo\CRMBundle\Entity\Circle:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    Members:
                        '':
                            contacts:
                                type: sonata_type_model_autocomplete
                                by_reference: false
                                property: name
                                multiple: true
                                required: false
                            organisms:
                                type: sonata_type_model_autocomplete
                                by_reference: false
                                property: name
                                multiple: true
                                required: false
                    _options:
                        tabsOrder:
                            - General
                            - Members
                            - Specifics
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    _action:
                        type: actions
                        actions:
                            show: ~
                            edit: ~
                            delete: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:


############
# POSITION
############

        Librinfo\CRMBundle\Entity\Position:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    General:
                        '':
                            contact:
                                required: true
                                placeholder: ''
                            position_type:
                                required: true
                                placeholder: ''
                            organism:
                                required: true
                                placeholder: ''
                            department: ~
                            phone: ~
                            description: ~
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    contact: ~
                    position-type: ~
                    organism: ~
                    _action:
                        type: actions
                        actions:
                            show: ~
                            edit: ~
                            delete: ~


#################
# POSITION_TYPE
#################

        Librinfo\CRMBundle\Entity\PositionType:
#            Sonata\AdminBundle\Form\FormMapper:
#                add:
#                    General:
#                        '':
#                            name: ~
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    name: ~
                    _action:
                        type: actions
                        actions:
                            show: ~
                            edit: ~
                            delete: ~
