parameters:
    librinfo:


############
# CATEGORY
############

        Librinfo\CRMBundle\Entity\Category:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            name:
                                type: text
                            parentNode:
                                type: librinfo_baseentities_treeable
                                class: Librinfo\CRMBundle\Entity\Category
                                required: false
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    name: ~


############
# ORGANISM
############

        Librinfo\CRMBundle\Entity\Organism:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                remove: [description]
                add:
                    form_group_general:
                        '':
                            category:
                                type: librinfo_baseentities_treeablechoice
                                class: Librinfo\CRMBundle\Entity\Category
                                required: false
                                multiple: false
                            url: ~
                            administrativeNumber: ~
                            description:
                                type: textarea
                                required: false
                        form_group_phones:
                            phones:
                                type: sonata_type_collection
                                by_reference: false
                                type_options:
                                    required: false
                                    btn_add: false
                                required: false
                                label: false
                                _options:
                                    edit: inline
                                    inline: table
                                    allow_delete: true
                    _options:
                        tabsOrder:
                            - form_group_general
                            - form_group_positions
                            - form_group_specifics
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [createdAt]
                add:
                    url: ~
                    category: ~
                    _options:
                        fieldsOrder:
                            - name
                            - email
                            - url
                            - zip
                            - city
                            - country
                            - category
                    _export_format:
                        csv: [name, address, zip, city, country, email, url, category, administrativeNumber, description, createdAt, updatedAt, vcardUid, npai, emailNpai, emailNoNewsletter, phones]
                        xls: csv
                        json: csv
                        xml: csv
                        vcard: [name, address, zip, city, country, email, url, description, phones, personal]
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    name: ~

###########
# CONTACT
###########

        Librinfo\CRMBundle\Entity\Contact:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
                add:
                    default:
                        _options:
                            groupsOrder:
                                - Contact
                                - form_group_phones
                                - form_group_address
                                - Description
                                - form_group_positions
                                - form_group_ticketing
                                - form_group_communication
                                - form_group_email
                                - form_group_misc
            Sonata\AdminBundle\Form\FormMapper:
                remove: [description]
                add:
                    form_group_general:
                        '':
                            title: ~
                            firstname: ~
                            description:
                                type: textarea
                                required: false
                            _options:
                                fieldsOrder:
                                    - title
                                    - firstname
                                    - name
                                    - email
                                    - circles
                                    - description
                        form_group_phones:
                            phones:
                                type: sonata_type_collection
                                by_reference: false
                                type_options:
                                    required: false
                                    btn_add: false
                                required: false
                                label: false
                                _options:
                                    edit: inline
                                    inline: table
                                    allow_delete: true
                        _options:
                            groupsOrder:
                                - ''
                                - form_group_phones
                                - Address
                    form_group_sales:
                        form_group_ticketing:
                            flashOnControl: ~
                    form_group_specifics:
                        form_group_communication:
                            culture: ~
                            _options:
                                fieldsOrder:
                                    - culture
                        _options:
                            groupsOrder:
                                - form_group_communication
                                - form_group_address
                                - form_group_email
                                - form_group_misc
                    _options:
                        tabsOrder:
                            - form_group_general
                            - form_group_positions
                            - form_group_sales
                            - form_group_specifics
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [createdAt]
                add:
                    title: ~
                    firstname: ~
                    _options:
                        fieldsOrder:
                            - title
                            - firstname
                            - name
                            - email
                    _list_action:
#                        duplicates:
#                            action: duplicates
#                            translation_domain: LibrinfoCRMBundle
#                        import:
#                            action: import
#                            translation_domain: LibrinfoCRMBundle
                    _export_format:
                        csv: [title, name, firstname, address, zip, city, country, email, description, createdAt, updatedAt, vcardUid, npai, emailNpai, emailNoNewsletter]
                        xls: csv
                        json: csv
                        xml: csv
                        vcard:
                            - firstname
                            - name
                            - address
                            - zip
                            - city
                            - country
                            - email
                            - description
                            - phones
                            - positions.label
                            - positions.phone
                            - positions.email
                            - positions.organism
                            - positions.organism.address
                            - positions.organism.zip
                            - positions.organism.city
                            - positions.organism.country
                            - personal
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    title: ~
                    firstname: ~
                    shortname: ~
                    familyContact: ~
                    culture: ~
                    npai: ~
                    emailNpai: ~
                    emailNoNewsletter: ~
                    _options:
                        fieldsOrder:
                            - title
                            - firstname
                            - name
                            - email
                            - zip
                            - city
                            - country
                            - familyContact
                            - culture
                            - npai
                            - emailNpai
                            - emailNoNewsletter

##########
# ORGANISMPHONE
##########

        Librinfo\CRMBundle\Entity\OrganismPhone:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    phoneType: ~
                    number: ~
                    organism: ~
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    organism: ~
                    phoneType: ~
                    number: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    number: ~
                    #organism: ~

##########
# CONTACTPHONE
##########

        Librinfo\CRMBundle\Entity\ContactPhone:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    phoneType: ~
                    number: ~
                    contact: ~
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    contact: ~
                    phoneType: ~
                    number: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    number: ~
                    #contact: ~

##########
# CIRCLE
##########

        Librinfo\CRMBundle\Entity\Circle:
            managedManyToMany: [contacts, organisms]
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                remove: [owner]
                add:
                    form_group_general:
                        '':
                            owner:
                                type: sonata_type_model_autocomplete
                                route: { name: searchable_admin_retrieve_autocomplete_items }
                                by_reference: false
                                property: username # not used but required
                                multiple: false
                                required: false
                            users:
                                type: sonata_type_model_autocomplete
                                route: { name: searchable_admin_retrieve_autocomplete_items }
                                by_reference: false
                                property: username # not used but required
                                multiple: true
                                required: false
                    form_group_members:
                        '':
                            contacts:
                                type: sonata_type_model_autocomplete
                                route: { name: searchable_admin_retrieve_autocomplete_items }
                                property: name # not used but required
                                by_reference: false
                                multiple: true
                                required: false
                            organisms:
                                type: sonata_type_model_autocomplete
                                route: { name: searchable_admin_retrieve_autocomplete_items }
                                property: name # not used but required
                                by_reference: false
                                multiple: true
                                required: false
                    _options:
                        tabsOrder:
                            - form_group_general
                            - form_group_members
                            - form_group_specifics
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    owner: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:


############
# POSITION
############

        Librinfo\CRMBundle\Entity\Position:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                remove: [email, label, emailNpai, emailNoNewsletter, circles, description]
                add:
                    '':
                        form_group_position:
                            contact:
                                type: sonata_type_model_autocomplete
                                route: { name: searchable_admin_retrieve_autocomplete_items }
                                by_reference: false
                                property: name # not used but required
                            organism:
                                type: sonata_type_model_autocomplete
                                route: { name: searchable_admin_retrieve_autocomplete_items }
                                by_reference: false
                                property: name # not used but required
                            positionType:
                                placeholder: ''
                            label: ~
                            email:
                                type: email
                            phone:
                                label: Phone number
                            circles: ~
                            department: ~
                            description:
                                type: textarea
                                required: false
                            _options:
                                fieldsOrder:
                                    - contact
                                    - organism
                                    - positionType
                                    - label
                                    - email
                                    - phone
                                    - circles
                                    - department
                                    - description
                        form_group_specifics:
                            emailNpai: ~
                            emailNoNewsletter: ~
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    contact: ~
                    position_type: ~
                    organism: ~

############
# CIRCLABLE Trait
############

        Librinfo\CRMBundle\Entity\Traits\Circlable:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            circles: ~
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    _export_format: [group]

############
# POSITIONABLE Trait
############

        Librinfo\CRMBundle\Entity\Traits\Positionable:
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    '':
                        form_group_positions:
                            positions:
                                _options:
                                    initializeAssociationAdmin: true
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_positions:
                        form_group_positions:
                            positions:
                                type: sonata_type_collection
                                by_reference: false
                                type_options:
                                    required: false
                                    btn_add: false
                                required: false
                                label: false
                                _options:
                                    edit: inline
                                    #inline: table
                                    allow_delete: true

#################
# POSITION_TYPE
#################

        Librinfo\CRMBundle\Entity\PositionType:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper

#################
# PHONE_TYPE
#################

        Librinfo\CRMBundle\Entity\PhoneType:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
