parameters:
    librinfo:
        Librinfo\CRMBundle\Admin\OrganismAdmin:     # Organisms
            Sonata\AdminBundle\Form\FormMapper:     # Form
                add:
                    General:
                        '':
                            categories:
                                type: sonata_type_model
                                property: name
                                required: false
                                multiple: true
            Sonata\AdminBundle\Datagrid\ListMapper: # Filters
                add:
                    categories: ~
        Librinfo\CRMBundle\Admin\ContactAdmin:      # Contacts
            Sonata\AdminBundle\Datagrid\ListMapper: # List
                add:
                    title: ~
                    firstname: ~
                    name: ~
                    email: ~
                    postalcode: ~
                    city: ~
                    country: ~
                    culture: ~
                    _action:
                        actions:
                            show: ~
                            edit: ~
                            delete: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper: # Filters
                add:
                    title: ~
                    name: ~
                    firstname: ~
                    address: ~
                    postalcode: ~
                    city: ~
                    country: ~
                    email: ~
                    shortname: ~
                    familyContact: ~
                    culture: ~
                    npai: ~
                    emailNpai: ~
                    emailNoNewsletter: ~
            Sonata\AdminBundle\Form\FormMapper:     # Form
                remove: [name, email]
                add:
                    General:
                        '':
                            title: ~
                            name: ~
                            firstname: ~
                            email: ~
                            _options:
                                fieldsOrder:
                                    - email
                                    - firstname
                                    - name
                                    - title
                    Ticketting:
                        History: ~
                        Control:
                            flashOnControl: ~
                    Specifics:
                        Communication:
                            culture: ~


