parameters:
    librinfo:
        Librinfo\CRMBundle\Entity\Contact:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    General:
                        _options:
                            groupsOrder:
                                - Address
                                - ''
                        '':
                            title: ~
                            firstname: ~
                            _options:
                                fieldsOrder:
                                   - title
                                   - firstname
                                   - name
                                   - email
                    Sales:
                        Ticketing:
                            flashOnControl: ~
                    Specifics:
                        Communication:
                            culture: ~
                            _options:
                                fieldsOrder:
                                    - culture
                    _options:
                        tabsOrder:
                            - General
                            - Sales
                            - Specifics
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    title: ~
                    firstname: ~
                    shortname: ~
                    familyContact: ~
                    culture: ~
                    npai: ~
                    emailNpai: ~
                    emailNoNewsletter: ~
                    _options:
                        fieldsOrder:
                            - title
                            - firstname
                            - name
                            - email
                            - zip
                            - city
                            - country
                            - familyContact
                            - culture
                            - npai
                            - emailNpai
                            - emailNoNewsletter
        
