parameters:
    librinfo:
        Librinfo\CRMBundle\Entity\Category:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    General:
                        '':
                            name:
                                type: text
                            parentNode:
                                type: treeable
                                class: Librinfo\CRMBundle\Entity\Category
                                required: false
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    name: ~
#                    nodeLevel: ~
                    _action:
                        type: actions
                        actions:
                            show: ~
                            edit: ~
                            delete: ~
        Librinfo\CRMBundle\Entity\Organism:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    Organism:
                        '':
                            url: ~
                            administrativeNumber: ~
                            categories:
                                type: treeable_choice
                                class: Librinfo\CRMBundle\Entity\Category
                                required: false
                                multiple: true
                    _options:
                        tabsOrder:
                            - Organism
                            - General
                            - Specifics
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    url: ~
                    administrativeNumber: ~
                    categories: ~
                    _action:
                        type: actions
                        actions:
                            show: ~
                            edit: ~
                            delete: ~
                remove:
                    - zip
                    - city
                    - country
                    - email
        Librinfo\CRMBundle\Entity\Contact:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    General:
                        '':
                            title: ~
                            firstname: ~
                            _options:
                                fieldsOrder:
                                   - title
                                   - firstname
                                   - name
                                   - email
                    Sales:
                        Ticketing:
                            flashOnControl: ~
                    Specifics:
                        Communication:
                            culture: ~
                            _options:
                                fieldsOrder:
                                    - culture
                    _options:
                        tabsOrder:
                            - General
                            - Sales
                            - Specifics
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    title: ~
                    firstname: ~
                    _options:
                        fieldsOrder:
                            - title
                            - firstname
                            - name
                            - email
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    title: ~
                    firstname: ~
                    shortname: ~
                    familyContact: ~
                    culture: ~
                    npai: ~
                    emailNpai: ~
                    emailNoNewsletter: ~
                    _options:
                        fieldsOrder:
                            - title
                            - firstname
                            - name
                            - email
                            - zip
                            - city
                            - country
                            - familyContact
                            - culture
                            - npai
                            - emailNpai
                            - emailNoNewsletter
        
