parameters:
    librinfo:
        Librinfo\CRMBundle\Entity\Category:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    General:
                        '':
                            name:
                                type: text
                            parentNode:
                                type: treeable
                                class: Librinfo\CRMBundle\Entity\Category
                                required: false
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    name: ~
                    _action:
                        type: actions
                        actions:
                            show: ~
                            edit: ~
                            delete: ~
                            
                            
        Librinfo\CRMBundle\Entity\Organism:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    Organism:
                        '':
                            url: ~
                            administrativeNumber: ~
                            categories:
                                type: treeable_choice
                                class: Librinfo\CRMBundle\Entity\Category
                                required: false
                                multiple: true
                    _options:
                        tabsOrder:
                            - Organism
                            - General
                            - Specifics
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    url: ~
                    administrativeNumber: ~
                    categories: ~
                    _action:
                        type: actions
                        actions:
                            show: ~
                            edit: ~
                            delete: ~
                remove:
                    - zip
                    - city
                    - country
                    - email
                    
                    
        Librinfo\CRMBundle\Entity\Contact:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    General:
                        '':
                            title: ~
                            firstname: ~
                            phones:
                                type: sonata_type_collection
                                type_options:
                                    by_reference: true
                                    delete: true
                                #by_reference: true
                                required: false
                                
                            _options:
                                fieldsOrder:
                                   - title
                                   - firstname
                                   - name
                                   - email   
                                   - phones
                    Sales:
                        Ticketing:
                            flashOnControl: ~
                    Specifics:
                        Communication:
                            culture: ~
                            _options:
                                fieldsOrder:
                                    - culture
                    _options:
                        tabsOrder:
                            - General
                            - Sales
                            - Specifics
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    title: ~
                    firstname: ~
                    _options:
                        fieldsOrder:
                            - title
                            - firstname
                            - name
                            - email
                    _action:
                        type: actions
                        actions:
                            show: ~
                            edit: ~
                            delete: ~                            
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    title: ~
                    firstname: ~
                    shortname: ~
                    familyContact: ~
                    culture: ~
                    npai: ~
                    emailNpai: ~
                    emailNoNewsletter: ~
                    _options:
                        fieldsOrder:
                            - title
                            - firstname
                            - name
                            - email
                            - zip
                            - city
                            - country
                            - familyContact
                            - culture
                            - npai
                            - emailNpai
                            - emailNoNewsletter
                            
                            
        Librinfo\CRMBundle\Entity\ContactPhone:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    number: ~       
                    contact: ~
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:     
                    number: ~
                    contact.firstname: ~
                    _action:
                        type: actions
                        actions:
                            show: ~
                            edit: ~
                            delete: ~                       
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    number: ~
                    #contact: ~
                    

        Librinfo\CRMBundle\Entity\Circle:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    #contacts: ~
                    organisms: ~
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:     
                    _action:
                        type: actions
                        actions:
                            show: ~
                            edit: ~
                            delete: ~                       
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
            