librinfo.security:
    # Checking Controllers and/or Services access
    method_access_control:
        'Librinfo\\UIBundle\\Twig\\Extension\\AdminMenu::showAdminMenu$': 'hasRole("CRM_MANAGER")'
    # Defining custom Roles hierarchy (as a tree)
    security.role_hierarchy.roles:
        ROLE_SUPER_ADMIN:
            - ROLE_CRM_MANAGER:
                - ROLE_CRM_CONTACT_MANAGER:
                    - ROLE_CRM_CONTACT_VIEWER:
                        - ROLE_CRM_CONTACT_LIST
                        - ROLE_CRM_CONTACT_VIEW
                        - ROLE_CRM_CONTACT_CREATE
                        - ROLE_CRM_CONTACT_EDIT
                        - ROLE_CRM_CONTACT_EXPORT